# GitHub Action to build a SQL project
name: Build SQL Project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-sql-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4