# GitHub Action to build an SDK-style SQL project
name: Build SDK-style SQL Project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-sql-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore Packages
        run: dotnet restore ./src/EmployeeDbSdk/EmployeeDbSdk.sqlproj
      - name: Build SQL Project
        run: dotnet build ./src/EmployeeDbSdk/EmployeeDbSdk.sqlproj --configuration Release /p:NetCoreBuild=true
      - name: Publish SQL Build Artifacts
        uses: actions/upload-artifact@v3
        with:
            name: sql-artifacts
            path: ./src/EmployeeDbSdk/bin/Release