# GitHub Action to build a SQL project
name: Build SQL Project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-sql-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download SQL Build Tools
        run: |
            # https://www.nuget.org/packages/Microsoft.Build.Sql
            curl -sSL -o /tmp/microsoft.build.sql.zip https://globalcdn.nuget.org/packages/microsoft.build.sql.0.1.12-preview.nupkg
            sudo apt-get install unzip
            mkdir /tmp/microsoft.build.sql
            unzip /tmp/microsoft.build.sql.zip -d /tmp/microsoft.build.sql
            cd /tmp/microsoft.build.sql/tools/netstandard2.1/
            mkdir $GITHUB_WORKSPACE/SqlBuildTools
            cp Microsoft.Data.SqlClient.dll \
            Microsoft.Data.Tools.Schema.Sql.dll \
            Microsoft.Data.Tools.Schema.SqlTasks.targets \
            Microsoft.Data.Tools.Schema.Tasks.Sql.dll \
            Microsoft.Data.Tools.Utilities.dll \
            Microsoft.SqlServer.Dac.dll \
            Microsoft.SqlServer.Dac.Extensions.dll \
            Microsoft.SqlServer.TransactSql.ScriptDom.dll \
            Microsoft.SqlServer.Types.dll \
            System.ComponentModel.Composition.dll \
            System.IO.Packaging.dll \
            $GITHUB_WORKSPACE/SqlBuildTools
            cd $GITHUB_WORKSPACE
            rm -r /tmp/microsoft.build.sql
      - name: Build SQL Project
        run: dotnet build ./src/EmployeeDb/EmployeeDb.sqlproj /p:NetCoreBuild=true /p:NETCoreTargetsPath="$GITHUB_WORKSPACE/SqlBuildTools"